version: "3.9"
services:
  app:
    build: .
    container_name: wb-tariffs-app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3001:3000"
    volumes:
      - ./src:/usr/src/app/src
    command: sh -c "npm run migrate && node dist/index.js"

  db:
    image: postgres:15-alpine
    container_name: wb-tariffs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      GOOGLE_APPLICATION_CREDENTIALS: AIzaSyBviqEacqf3GRQ2TcfssupKM1QP2pGDxMQ

    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
